---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aws-example-octodex
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - name: aws-example-octodex
        image: 499180507218.dkr.ecr.eu-west-2.amazonaws.com/example-eks:e77f3d7e5c1e12e8137c979110ccb47b20d7e5bf
        #image: REGISTRY/IMAGE:TAG
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
